import React, { useEffect, useState } from "react";
import { API, graphqlOperation, Storage, Analytics, Auth, Amplify } from "aws-amplify";

import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Card, Button, Text, Flex, Grid, View, Heading, useTheme, Authenticator } from "@aws-amplify/ui-react";
import { listTodos } from "../src/graphql/queries";
import config from "../src/aws-exports";
import "@aws-amplify/ui-react/styles.css";

Amplify.configure(config);

export default function Home() {
  const [todos, setTodos] = useState([]);
  const { tokens } = useTheme();

  useEffect(() => {
    async function getTodos() {
      try {
        const result = await API.graphql(graphqlOperation(listTodos));
        console.log("data", result.data.listTodos.items);
        if (result) {
          setTodos(result.data.listTodos.items);
        }
      } catch (err) {
        console.log(err);
      }
    }
    getTodos();
  }, []);

  return (
    <View padding="20px">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Heading level={1}>Welcome to Amplify Migrate</Heading>
        <Authenticator>
          {({ signOut, user }) => (
            <main>
              <h1>Hello {user.username}</h1>
              <button onClick={signOut}>Sign out</button>
              {todos &&
                todos.map((todo, index) => {
                  return (
                    <Card
                      key={index}
                      padding="10px"
                      borderRadius={"10px"}
                      backgroundColor={"lightpink"}
                      height={"200px"}
                      width={"300px"}
                      border="2px solid black"
                      boxShadow={"10px 10px 5px 0px rgba(0,0,0,0.75)"}
                    >
                      {todo.name}
                    </Card>
                  );
                })}
            </main>
          )}
        </Authenticator>
      </main>
    </View>
  );
}
